#pragma once

#include <set>
#include <string>
#include <vector>

inline size_t tag_size;
inline std::vector<std::string> frameTags = {
	"TSTU",
	"TCMP",
	"TMED",
	"TDAT",
	"TSO2",
	"COMM",
	"COMR",
	"ENCR",
	"EQU2",
	"ETCO",
	"GRID",
	"LINK",
	"OWNE",
	"PRIV",
	"PCNT",
	"POPM",
	"POSS",
	"RBUF",
	"RVA2",
	"SEEK",
	"SYLT",
	"TALB",
	"TBPM",
	"TCOM",
	"TCON",
	"TCOP",
	"TDEN",
	"TDLY",
	"TDOR",
	"TDRC",
	"TDRL",
	"TDTG",
	"TENC",
	"TEXT",
	"TIPL",
	"TIT1",
	"TIT2",
	"TIT3",
	"TKEY",
	"TLAN",
	"TLEN",
	"TMCL",
	"TMOO",
	"TOAL",
	"TOFN",
	"TOLY",
	"TOPE",
	"TOWN",
	"TPE1",
	"TPE2",
	"TPE3",
	"TPE4",
	"TPOS",
	"TPRO",
	"TPUB",
	"TRCK",
	"TRSN",
	"TRSO",
	"TSOA",
	"TSOP",
	"TSOT",
	"TSRC",
	"TSSE",
	"TSST",
	"TYER",
	"TXXX",
	"UFID",
	"USER",
	"USLT",
	"WCOM",
	"WCOP",
	"WOAF",
	"WOAR",
	"WOAS",
	"WORS",
	"WPAY",
	"WPUB",
	"WXXX"
};
inline std::set<std::string> Identity_Info = {
	"TSO2",
	"TALB",
	"TBPM",
	"TCOM",
	"TCON",
	"TCOP",
	"TDEN",
	"TDLY",
	"TDOR",
	"TDRC",
	"TDRL",
	"TSOT",
	"TDTG",
	"TENC",
	"TEXT",
	"TFLT",
	"TIPL",
	"TIT1",
	"TIT2",
	"TIT3",
	"TKEY",
	"TLAN",
	"TLEN",
	"TMCL",
	"TMED",
	"TMOO",
	"TOAL",
	"TOFN",
	"TOLY",
	"TOPE",
	"TOWN",
	"TPE1",
	"TPE2",
	"TPE3",
	"TPE4",
	"TPOS",
	"TPRO",
	"TPUB",
	"TRCK",
	"TRSN",
	"TRSO",
	"TSOA",
	"TSOP",
	"TSRC",
	"TSSE",
	"TSST",
};
inline std::set<std::string> Audio_Characteristics = {"AENC", "ASPI", "EQU2", "ETCO", "MLLT", "RVA2", "RVRB", "SEEK", "SYLT", "SYTC", "TYER", "TCMP", "TMED", "TDAT"};
inline std::set<std::string> Attached_Picture_and_Visual_Information = {"APIC", "GEOB", "PIC"};
inline std::set<std::string> Comments_and_Other_Information = {"COMM", "PCNT", "POPM", "USER", "USLT"};
inline std::set<std::string> Commercial_Information = {"COMR", "WCOM", "TSTU"};
inline std::set<std::string> Encryption_and_Security = {"ENCR", "SIGN", "ENCRYPTED"};
inline std::set<std::string> Linked_Information = {"LINK"};
inline std::set<std::string> Miscellaneous = {"RBUF", "OWNE", "PRIV", "GRID", "MCDI", "SIGNATURE", "UFID", "WXXX", "TXXX", "APIC", "GEOB", "PCNT", "POPM", "RVRB"};
inline std::set<std::string> OfficialInfo = {"WOAF", "WOAR", "WOAS ", "WORS", "WPUB"};
